# Generated by Django 5.1.2 on 2024-12-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLocker',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.TextField()),
                ('file_name', models.TextField()),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_locker.usercredentials')),
            ],
        ),
    ]
