# Generated by Django 5.1.2 on 2024-12-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_locker', '0002_usercredentials_groups_usercredentials_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
