# Generated by Django 5.1.2 on 2024-12-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_locker', '0003_usercredentials_is_staff_alter_usercredentials_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='role',
            field=models.TextField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient'),
            preserve_default=False,
        ),
    ]
