# Generated by Django 5.1.2 on 2024-12-09 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_locker', '0004_usercredentials_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
