# Generated by Django 5.1.2 on 2024-12-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_locker', '0006_alter_datarequests_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequests',
            old_name='approved',
            new_name='status',
        ),
    ]
