# Generated by Django 5.1.2 on 2024-12-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_locker', '0010_alter_datarequests_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequests',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
