# Generated by Django 5.1.2 on 2025-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_locker', '0011_alter_datarequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequests',
            name='request_date',
            field=models.TextField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
